from pathlib import Path
mH_settings=    {'no_chs': 2, 
                'name_chs':
                     {'ch1': 'myoc', 
                      'ch2': 'endo', 
                      'chNS': 'cardiac jelly'}, 
                'chs_relation': 
                    {'ch1': 'external', 
                     'ch2': 'internal'}, 
                'color_chs':
                    {'ch1':
                            {'int': 'gold', 
                            'tiss': 'lightseagreen', 
                            'ext': 'crimson'}, 
                    'ch2': 
                            {'int': 'deepskyblue', 
                            'tiss': 'darkmagenta', 
                            'ext': 'deeppink'}}, 
                'mask_ch':
                        {'ch1': True, 
                         'ch2': True},
                'orientation': 
                    {'stack': 'anterior, ventral, left', 
                     'roi': 'anterior, ventral, left'},
                'rotateZ_90': True, 
                'chNS': 
                    {'layer_btw_chs': True, 
                     'ch_ext': ('ch1', 'int'), 
                     'ch_int': ('ch2', 'ext'), 
                     'user_nsChName': 'cardiac jelly', 
                     'color_chns': 
                            {'int': 'greenyellow', 
                            'tiss': 'darkorange', 
                            'ext': 'powderblue'}}, 
                'segm': {'cutLayersIn2Segments': True, 
                        'Cut1': 
                                {'no_segments': 2, 
                                'obj_segm': 'Disc', 
                                'no_cuts_4segments': 1, 
                                'name_segments':
                                        {'segm1': 'atrium', 
                                        'segm2': 'ventricle'}, 
                                'ch_segments':
                                        {'ch1': ['tiss', 'ext'], 
                                        'ch2': ['int', 'tiss'], 
                                        'chNS': ['tiss']}}, 
                        'measure': 
                                {'volume': True, 
                                'area': True, 
                                'ellipsoids': True}}, 
                'sect': {'cutLayersIn2Sections': True, 
                        'Cut1': 
                            {'no_sections': 2, 
                            'obj_segm': 'Centreline', 
                            'name_segments':
                                    {'sect1': 'left',
                                     'sect2': 'right'}, 
                            'ch_segments': 
                                    {'ch1': ['tiss'],
                                     'ch2': ['tiss'],
                                     'chNS': ['tiss']}}, 
                        'measure': 
                                {'volume': True, 
                                 'area': False}}}

proj = {'mH_projName': 'mH_Proj-202304271755', 
        'user_projName': 'test_project', 
        'info': 
            {'mH_projName': 'mH_Proj-202304271755', 
             'user_projName': 'test_project', 
             'user_projNotes': '', 
             'date_created': '2023-04-27', 
             'dirs': []},
        'analysis': 
            {'morphoHeart': True,
            'morphoCell': False, 
            'morphoPlot': False}, 
        'dir_proj': Path('D:/Documents JSP/Dropbox/Dropbox_Juliana/morphoHeart_rev/images/R_test project'), 
        'organs': {}, 
        'cellGroups': {}}

meas_param = {'ch1:int:whole:SA': False, 
              'ch1:tiss:whole:SA': False, 
              'ch1:ext:whole:SA': False, 
              'ch2:int:whole:SA': False, 
              'ch2:tiss:whole:SA': False, 
              'ch2:ext:whole:SA': False, 
              'chNS:int:whole:SA': False, 
              'chNS:tiss:whole:SA': False, 
              'chNS:ext:whole:SA': False, 
              'ch1:int:whole:Vol': True, 
              'ch1:tiss:whole:Vol': True, 
              'ch1:ext:whole:Vol': True, 
              'ch2:int:whole:Vol': True, 
              'ch2:tiss:whole:Vol': True, 
              'ch2:ext:whole:Vol': True, 
              'chNS:int:whole:Vol': True, 
              'chNS:tiss:whole:Vol': True, 
              'chNS:ext:whole:Vol': True, 
              'ch1:int:whole:CL': True, 
              'ch1:tiss:whole:CL': False, 
              'ch1:ext:whole:CL': False, 
              'ch2:int:whole:CL': False, 
              'ch2:tiss:whole:CL': False, 
              'ch2:ext:whole:CL': False, 
              'chNS:int:whole:CL': False, 
              'chNS:tiss:whole:CL': False, 
              'chNS:ext:whole:CL': False, 
              'ch1:int:whole:CLlin': True, 
              'ch1:tiss:whole:CLlin': False, 
              'ch1:ext:whole:CLlin': False, 
              'ch2:int:whole:CLlin': False, 
              'ch2:tiss:whole:CLlin': False, 
              'ch2:ext:whole:CLlin': False, 
              'chNS:int:whole:CLlin': False, 
              'chNS:tiss:whole:CLlin': False, 
              'chNS:ext:whole:CLlin': False, 
              'ch1:int:whole:CLloop': True, 
              'ch1:tiss:whole:CLloop': False, 
              'ch1:ext:whole:CLloop': False, 
              'ch2:int:whole:CLloop': False, 
              'ch2:tiss:whole:CLloop': False, 
              'ch2:ext:whole:CLloop': False, 
              'chNS:int:whole:CLloop': False, 
              'chNS:tiss:whole:CLloop': False, 
              'chNS:ext:whole:CLloop': False, 
              'ch1:int:whole:th_i2e': False, 
              'ch1:tiss:whole:th_i2e': True, 
              'ch1:ext:whole:th_i2e': False, 
              'ch2:int:whole:th_i2e': False, 
              'ch2:tiss:whole:th_i2e': True, 
              'ch2:ext:whole:th_i2e': False, 
              'chNS:int:whole:th_i2e': False, 
              'chNS:tiss:whole:th_i2e': True, 
              'chNS:ext:whole:th_i2e': False, 
              'ch1:int:whole:th_e2i': False, 
              'ch1:tiss:whole:th_e2i': False, 
              'ch1:ext:whole:th_e2i': False, 
              'ch2:int:whole:th_e2i': False, 
              'ch2:tiss:whole:th_e2i': False, 
              'ch2:ext:whole:th_e2i': False, 
              'chNS:int:whole:th_e2i': False, 
              'chNS:tiss:whole:th_e2i': False, 
              'chNS:ext:whole:th_e2i': False, 
              'ch1:int:whole:bal': True, 
              'ch1:tiss:whole:bal': False, 
              'ch1:ext:whole:bal': False, 
              'ch2:int:whole:bal': False, 
              'ch2:tiss:whole:bal': False, 
              'ch2:ext:whole:bal': False, 
              'chNS:int:whole:bal': False, 
              'chNS:tiss:whole:bal': False, 
              'chNS:ext:whole:bal': False, 
              'ch1:int:whole:looping_direction': False, 
              'ch1:tiss:whole:looping_direction': False, 
              'ch1:ext:whole:looping_direction': True, 
              'ch2:int:whole:looping_direction': False, 
              'ch2:tiss:whole:looping_direction': False, 
              'ch2:ext:whole:looping_direction': False, 
              'chNS:int:whole:looping_direction': False, 
              'chNS:tiss:whole:looping_direction': False, 
              'chNS:ext:whole:looping_direction': False}