# Form implementation generated from reading ui file 'C:\Users\Noel\Desktop\prompt_ok_cancel_radio.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(401, 358)
        Dialog.setStyleSheet("QDialog{background-color: rgb(255, 255, 255);}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.mH_logo_XS = QtWidgets.QLabel(parent=Dialog)
        self.mH_logo_XS.setMinimumSize(QtCore.QSize(120, 30))
        self.mH_logo_XS.setMaximumSize(QtCore.QSize(120, 30))
        self.mH_logo_XS.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.mH_logo_XS.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.mH_logo_XS.setObjectName("mH_logo_XS")
        self.horizontalLayout.addWidget(self.mH_logo_XS, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.textEdit = QtWidgets.QTextEdit(parent=Dialog)
        self.textEdit.setStyleSheet("QTextEdit {background-color: rgba(0,0,0,0);\n"
"font: 25 11pt \"Calibri Light\";\n"
"font-family: \"Calibri Light\";\n"
"}\n"
"\n"
"                    ")
        self.textEdit.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_2.addWidget(self.textEdit)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.widget = QtWidgets.QWidget(parent=Dialog)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.hL0 = QtWidgets.QHBoxLayout()
        self.hL0.setObjectName("hL0")
        self.radioButton0 = QtWidgets.QRadioButton(parent=self.widget)
        self.radioButton0.setMinimumSize(QtCore.QSize(0, 20))
        self.radioButton0.setMaximumSize(QtCore.QSize(16777215, 20))
        self.radioButton0.setStyleSheet("font: 25 10pt \"Calibri Light\";")
        self.radioButton0.setObjectName("radioButton0")
        self.hL0.addWidget(self.radioButton0)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.hL0.addItem(spacerItem2)
        self.lineEdit0 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit0.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit0.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lineEdit0.setObjectName("lineEdit0")
        self.hL0.addWidget(self.lineEdit0)
        self.verticalLayout.addLayout(self.hL0)
        self.hL1 = QtWidgets.QHBoxLayout()
        self.hL1.setObjectName("hL1")
        self.radioButton1 = QtWidgets.QRadioButton(parent=self.widget)
        self.radioButton1.setMinimumSize(QtCore.QSize(0, 20))
        self.radioButton1.setMaximumSize(QtCore.QSize(16777215, 20))
        self.radioButton1.setStyleSheet("font: 25 10pt \"Calibri Light\";")
        self.radioButton1.setObjectName("radioButton1")
        self.hL1.addWidget(self.radioButton1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.hL1.addItem(spacerItem3)
        self.lineEdit1 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit1.setMinimumSize(QtCore.QSize(0, 20))
        self.lineEdit1.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lineEdit1.setObjectName("lineEdit1")
        self.hL1.addWidget(self.lineEdit1)
        self.verticalLayout.addLayout(self.hL1)
        self.horizontalLayout_3.addWidget(self.widget)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setStyleSheet("QDialogButtonBox QPushButton{\n"
"color: rgb(39, 39, 39);\n"
"font: 11pt \"Calibri Light\";\n"
"height:20;\n"
"padding:0px;\n"
"width:90;\n"
"background-color: rgb(211, 211, 211);\n"
"border-radius: 10px;\n"
"border-width: 1px;\n"
"border-style: outset;\n"
"border-color: rgb(66, 66, 66);\n"
"}\n"
"\n"
"QDialogButtonBox QPushButton:hover{\n"
"background-color: #eb6fbd;\n"
"border-color: #672146\n"
"}\n"
"\n"
"")
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox, 0, QtCore.Qt.AlignmentFlag.AlignRight)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.mH_logo_XS.setText(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>"))
        self.textEdit.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Calibri Light\'; font-size:11pt; font-weight:24; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">XXX</p></body></html>"))
        self.radioButton0.setText(_translate("Dialog", "RadioButton"))
        self.radioButton1.setText(_translate("Dialog", "RadioButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
