# Form implementation generated from reading ui file 'C:\Users\Noel\Desktop\tests.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.checkBox0 = QtWidgets.QCheckBox(parent=Dialog)
        self.checkBox0.setGeometry(QtCore.QRect(90, 60, 15, 20))
        self.checkBox0.setMinimumSize(QtCore.QSize(15, 20))
        self.checkBox0.setMaximumSize(QtCore.QSize(15, 20))
        self.checkBox0.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.checkBox0.setStyleSheet("font: 25 10pt \"Calibri Light\";")
        self.checkBox0.setText("")
        self.checkBox0.setObjectName("checkBox0")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
